### ISSUE TITLE
EP und Currency Sprite erstellen

### ISSUE THREAD

**Issue by Andrushka130** [Andrushka130/WASD#73]
Die Sprites für EP und Currency erstellen. EP und Currency sollen unterschieden werden können. Außerdem sollen sie einen unsichtbaren Radius haben, der bei Berührung die EP und Eurodollar anziehen

**Comment by TimBreunig** [comment]
![Eurodollar Sprite](https://user-images.githubusercontent.com/118123422/213688152-baab37d0-c097-44b1-86d8-7e0db0834be5.png)
![Exp Sprite](https://user-images.githubusercontent.com/118123422/213688175-d2a11678-1ccb-4e6d-b1cc-2c38f701fdab.png)
